-- FundiConnect Pro initial relational schema. Applied once by the migration runner.
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY, full_name text NOT NULL CHECK (char_length(full_name) BETWEEN 2 AND 100), email text UNIQUE, phone text UNIQUE, password_hash text NOT NULL, role text NOT NULL DEFAULT 'customer' CHECK (role IN ('customer','fundi','company','admin')), is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK (email IS NOT NULL OR phone IS NOT NULL));
CREATE TABLE IF NOT EXISTS categories (id uuid PRIMARY KEY, name text NOT NULL UNIQUE, slug text NOT NULL UNIQUE, description text NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS fundi_profiles (id uuid PRIMARY KEY, user_id uuid NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE, category_id uuid REFERENCES categories(id), professional_title text NOT NULL DEFAULT 'Skilled Professional', bio text NOT NULL DEFAULT '', county text NOT NULL DEFAULT '', town text NOT NULL DEFAULT '', years_experience integer NOT NULL DEFAULT 0 CHECK (years_experience BETWEEN 0 AND 70), skills text[] NOT NULL DEFAULT '{}', available boolean NOT NULL DEFAULT true, verification_level text NOT NULL DEFAULT 'none' CHECK (verification_level IN ('none','bronze','silver','gold','platinum')), phone_verified boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS bookings (id uuid PRIMARY KEY, customer_id uuid NOT NULL REFERENCES users(id), fundi_id uuid NOT NULL REFERENCES fundi_profiles(id), service_title text NOT NULL CHECK (char_length(service_title) BETWEEN 3 AND 120), description text NOT NULL CHECK (char_length(description) BETWEEN 5 AND 3000), county text NOT NULL DEFAULT '', town text NOT NULL DEFAULT '', scheduled_at timestamptz, status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','assigned','traveling','in_progress','completed','cancelled')), quoted_price numeric(12,2) CHECK (quoted_price IS NULL OR quoted_price >= 0), customer_note text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), accepted_at timestamptz, completed_at timestamptz);
CREATE TABLE IF NOT EXISTS reviews (id uuid PRIMARY KEY, booking_id uuid NOT NULL UNIQUE REFERENCES bookings(id) ON DELETE CASCADE, customer_id uuid NOT NULL REFERENCES users(id), fundi_id uuid NOT NULL REFERENCES fundi_profiles(id), rating integer NOT NULL CHECK (rating BETWEEN 1 AND 5), professionalism integer NOT NULL CHECK (professionalism BETWEEN 1 AND 5), speed integer NOT NULL CHECK (speed BETWEEN 1 AND 5), communication integer NOT NULL CHECK (communication BETWEEN 1 AND 5), quality integer NOT NULL CHECK (quality BETWEEN 1 AND 5), value_score integer NOT NULL CHECK (value_score BETWEEN 1 AND 5), comment text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS user_sessions (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS notifications (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, type text NOT NULL, title text NOT NULL, body text NOT NULL, booking_id uuid REFERENCES bookings(id) ON DELETE CASCADE, read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_logs (id uuid PRIMARY KEY, actor_user_id uuid REFERENCES users(id) ON DELETE SET NULL, action text NOT NULL, entity_type text NOT NULL, entity_id text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_users_role_active ON users(role, is_active);
CREATE INDEX IF NOT EXISTS idx_fundi_category_location ON fundi_profiles(category_id, county, town, available);
CREATE INDEX IF NOT EXISTS idx_fundi_user_id ON fundi_profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_bookings_customer_created ON bookings(customer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bookings_fundi_status ON bookings(fundi_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reviews_fundi_created ON reviews(fundi_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON user_sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at DESC);
